### ISSUE TITLE
PhysicalDrive0  vs C:

### ISSUE THREAD

**Issue by muteb** [ColinFinck/ntfs#8]
Hi Colin,

I have a question that drives me nuts :) and it has no thing to do with the framework at all rather it might clear some concepts on my head. When reading through Microsoft documentation, I fully understand that to access the physical raw of a disk and getting a handle of the MBR file, you will need to specify the path as \\.\PhysicalDrive0 and you managed to do it through \\.\C: . Is it possible to do it both or what it is the idea behind that... 

Thanks in advance and apology for writing this as an issue.

**Comment by ColinFinck** [comment]
`\\.\C:` is a partition of a drive, `\\.\PhysicalDrive0` is the drive itself (which contains all partitions).
Alternatively, I could have used `\\.\Harddisk0Partition4` instead of `\\.\C:`. Browse the "GLOBAL??" namespace with [Sysinternals WinObj](https://docs.microsoft.com/en-us/sysinternals/downloads/winobj) to find out about all aliases you can use.

**Comment by muteb** [comment]
Ok that explain it very well. appricaite it.

Thanks,
